playpauseandstop/rororo

README.rst

Small issue in README, that appear after the branch was deleted.

Fix wrong link in the README

---

.github/workflows/ci.yml
Makefile
examples/hobotnica/README.rst
examples/petstore/README.rst
examples/todobackend/README.rst
examples/todobackend/app.py
examples/todobackend/constants.py
examples/todobackend/data.py
examples/todobackend/openapi.yaml
examples/todobackend/settings.py
examples/todobackend/storage.py
examples/todobackend/tests.py
examples/todobackend/validators.py
examples/todobackend/views.py
poetry.lock
pyproject.toml
pytest.ini
rororo/openapi/openapi.py

This will help to ensure that further class based views support works as expected.
Issue: #15, #45

chore(examples): Provide Todo-Backend impelmentation

---

rororo/openapi/openapi.py
tests/test_openapi_core_data.py
tests/test_openapi_openapi.py

As well as increase test coverage for some of lately added code.

feature(openapi): Allow to add operations via `+` and `+=` arithmetic operations

---

pytest.ini
rororo/openapi/core_validators.py
rororo/openapi/exceptions.py
tests/openapi.json
tests/openapi.yaml
tests/test_openapi.py
tests/test_openapi_exceptions.py

- Handle parameter cast errors
- For any OpenAPI error supply error messages instead of handling only known errors

feature(openapi): Improve error handling

---

CHANGELOG.rst
README.rst

- Use `environ-config` for settings needs, instead of providing extra sugar to `attrs`
- Upgrade to latest `openapi-core==0.13.3`
- Support class based views
- Deprecate old approach of validating OpenAPI requests via `openapi_operation` decorator in favor of `openapi_middleware`. Improvements to error middleware, validate error responses against OpenAPI schema as well
- Valid request data is freezed with `pyrsistent.freeze` call. Parameters and security data wrapped into `pyrsistent.pmap` for immutability needs
- Use `email-validator` to support `format: "email"`
- Ensure TZ aware date times works as expected
- Ensure support of optional security schemes
- Provide `Todo-Backend` example to illustrate how to use class based views
- Update pre-commit hooks, integrate `blacken-docs` & …

chore(release): 2.0.0rc0 Release

---

pyproject.toml
rororo/__init__.py
tests/openapi.json
tests/openapi.yaml

Which has been missed in previous commit :(

chore: Bump version

---

CHANGELOG.rst
Makefile
docs/requirements.in
docs/requirements.txt

This allows to rebuild docs right after changes in source files.

docs: Use sphinx-autobuild for building docs at local env

---

.pre-commit-config.yaml
CHANGELOG.rst
examples/petstore/data.py
pyproject.toml
rororo/__init__.py
rororo/annotations.py
rororo/openapi/exceptions.py
tests/openapi.json
tests/openapi.yaml

And integrate `flake8-variable-names` plugin.

style: Update pre-commit hooks to use

---

.pre-commit-config.yaml
rororo/aio.py
rororo/openapi/core_data.py
rororo/openapi/security.py
rororo/openapi/utils.py

As well as bump pre-commit hooks versions.

style: Cast return values instead of type ignore comments

---

.github/workflows/ci.yml
.pre-commit-config.yaml
Makefile
README.rst
docs/conf.py
docs/index.rst
docs/openapi.rst
docs/openapi_errors.rst
docs/openapi_issues.rst
docs/openapi_speedups.rst
docs/requirements.in
docs/requirements.txt
docs/settings.rst
poetry.lock
pyproject.toml
rororo/__init__.py
rororo/logger.py
rororo/openapi/__init__.py
rororo/openapi/core_validators.py
rororo/openapi/openapi.py
tests/openapi.json
tests/openapi.yaml

As well as,
- Bump project & docs deps
- Fix version
- Bump pre-commit hooks
Fixes: #76

docs: Update docs with new rororo slogan

---

.github/workflows/ci.yml

ci: Create GitHub release at pushing git tag

---

.github/workflows/ci.yml

ci: Preserve multiline strings in release body

---

.github/workflows/ci.yml
.github/workflows/release_pr.yml
.github/workflows/release_tag.yml
CHANGELOG.rst
docs/changelog.rst
pyproject.toml
src/rororo/__init__.py
tests/openapi.json
tests/openapi.yaml

Automate process of creating releases for `rororo` by integrating `badabump` into CI workflows.

ci: Integrate badabump for release needs

---

.github/workflows/ci.yml

As it is only confuse new commiters (if any).
Fixes: #112

ci: Do not enforce commitizen check at CI

---

.pre-commit-config.yaml

Bump various hooks & keep mypy args in pre-commit hook.

style: Several updates to pre-commit hooks

---

Makefile
README.rst
docs/changelog.rst
docs/conf.py

As well as set proper dark theme for the docs.

docs: Tweak documentation

---

README.rst
docs/index.rst
docs/openapi_errors.rst

Made my best to find the other two broken links since it's my third day and third pull request since I've become a rororo user.

Fix docs links

---

examples/hobotnica/src/hobotnica/app.py
examples/petstore/src/petstore/app.py
examples/simulations/src/simulations/app.py
examples/todobackend/src/todobackend/app.py
poetry.lock
pyproject.toml
src/rororo/aio.py
src/rororo/logger.py
src/rororo/openapi/annotations.py
src/rororo/openapi/core_validators.py
src/rororo/openapi/exceptions.py
src/rororo/openapi/middlewares.py
src/rororo/openapi/openapi.py
src/rororo/settings.py
src/rororo/timedelta.py
src/rororo/utils.py

Which has been introduced in `mypy==0.981` and make sure proper type annotations for args / kwargs with default `None` values.

style: Enforce mypy no-implicit-optional setting

---

.pre-commit-config.yaml
examples/petstore/src/petstore/data.py
src/rororo/aio.py
src/rororo/logger.py
src/rororo/openapi/core_data.py
src/rororo/openapi/core_validators.py
src/rororo/openapi/exceptions.py
src/rororo/openapi/openapi.py
src/rororo/openapi/security.py
src/rororo/openapi/utils.py
src/rororo/settings.py
src/rororo/timedelta.py

To replace `Optional[T]` type annotations in code base to `Union[T, None]`

style: Introduce no-optional pre-commit hook

---

.github/actions/install_badabump/action.yml
.github/actions/install_python_and_poetry/action.yml
.github/actions/run_pre_commit/action.yml
.github/actions/run_tox/action.yml
.github/workflows/ci.yml
.github/workflows/ci_package.yml
.github/workflows/ci_release.yml
.github/workflows/ci_verify_docs_build.yml
.github/workflows/release_pr.yml
.github/workflows/release_tag.yml

To use latest possible actions versions.

ci: Update CI workflows & composite actions

---

src/rororo/settings.py
tests/rororo/test_settings.py

As previous commit broke it :(
Related: #360

fix(settings): Ensure `setup_settings_from_environ` function works well
