- examples/hobotnica/app.py
- examples/hobotnica/openapi.yaml
- examples/petstore/app.py
- rororo/openapi/openapi.py
- tests/openapi.json
- tests/openapi.yaml
- tests/test_openapi.py
Completely remove `route_prefix` keyword arg from `setup_openapi` func, use `server_url` instead.
Other way of setting up server URL to use is wrapping `aiohttp.web` application into `setup_settings` and marking each server schema definition with custom `x-rororo-level` key.
Fixes: #23
> feature(openapi): Guess route prefix from servers schema.

- CHANGELOG.rst
- rororo/openapi/security.py
- tests/openapi.json
- tests/openapi.yaml
- tests/test_openapi.py
When operation is optionally secured, it is need to ensure that security
rules properly enforced.
Fixes: #29
> feature(openapi): Ensure support of optional security schemes.

- CHANGELOG.rst
- docs/api.rst
- docs/settings.rst
- examples/hobotnica/app.py
- examples/petstore/app.py
- examples/petstore/settings.py
- poetry.lock
- pyproject.toml
- rororo/__init__.py
- rororo/settings.py
- tests/test_openapi.py
- tests/test_settings.py
Instead of wrapping settings into bare `@attr.dataclass` decorator, wrap
`rororo.settings.BaseSettings` and all inherited classes into `@environ.config`
decorator.
This allows use `environ.var` & `environ.bool_var` attributes instead of
`env_factory` custom factory.
Fixes: #33
> feature: Integrate `environ-config` for settings needs

- .github/workflows/ci.yml
- poetry.lock
- pyproject.toml
As it only installed at CI via `pip`.
Also setup env vars for CI job to simplify version management.
> chore: Properly do not depend on coveralls anymore

- examples/hobotnica/data.py
- examples/hobotnica/openapi.yaml
- examples/hobotnica/tests.py
- examples/hobotnica/views.py
- rororo/openapi/data.py
- rororo/openapi/validators.py
To ensure proper logic behind matching current request to OpenAPI operation to use.
`openapi-core==0.13.3` version ships with `openapi_core.templating.paths.finders.PathFinder` class, which finds too many paths if OpenAPI schema contains multiple paths with variables.
Given commit customize path finder logic to not return first result of `PathFinder._get_servers_iter(...)` call, but to match that current request full URL pattern ends with `Path.name`.
After fixing https://github.com/p1c2u/openapi-core/issues/226, this code might be not needed anymore.
Also provide docstrings for reason behind providing custom classes for validation, unmarshalling data, etc.
> fix(openapi): Use custom path finder

- CHANGELOG.rst
- README.rst
- examples/todobackend/data.py
- examples/todobackend/openapi.yaml
- examples/todobackend/tests.py
- examples/todobackend/views.py
- rororo/openapi/openapi.py
Ensure class based views is able to decorate with `@operations.register`
As of now it supports 2 modes,
1. When OpenAPI schema contains operation ID of `ViewMethod.__qualname__`
2. When OpenAPI schema contains operation ID of `<base>.<ViewMethod.__name__>`
Going forward it will be added 3rd mode to support decorating both `web.View`
and `ViewMethod` to allow register operation ID of custom name for the
`ViewMethod`.
----
In,
```python
class UserView(web.View):
async def get(self) -> web.Response:
...
```
`ViewMethod.__qualname__` is `UserView.get`.
Issue: #45
> feature(openapi): Support class based views as well

- CHANGELOG.rst
- docs/api.rst
- docs/openapi.rst
- examples/todobackend/openapi.yaml
- examples/todobackend/tests.py
- examples/todobackend/views.py
- rororo/annotations.py
- rororo/openapi/contexts.py
- rororo/openapi/data.py
- rororo/openapi/openapi.py
This commit finishes class based views support for `rororo` as it allows to provide custom operation ID for any view method as,
```python
@operations.register
class UserView(web.View):
@operations.register("me")
async def get(self) -> web.Response:
...
```
Update Todo-Backend example implementation to cover all possible ways of registering class based views as OpenAPI operation handlers.
Fixes: #45
> feature(openapi): Support custom operation ID on registering view method

- examples/hobotnica/app.py
- rororo/openapi/middlewares.py
- tests/test_openapi.py
If any other middlewares declared after openapi middleware it results that received handler will be an instance of `functools.partial`.
Need to unwrap partial, to try to find openapi mapping in actual handler, not a partial.
> feature(openapi): Get actual handler in openapi middleware

- examples/hobotnica/openapi.yaml
- examples/hobotnica/tests.py
- rororo/openapi/core_validators.py
- rororo/openapi/exceptions.py
`openapi-core==0.13.3` does not include param name in schema errors on unmarshalling values. This results in reduced error locations and as result in bad UX.
For example, previously, when param `name` has invalid value, `rororo` will provide,
```json
{"detail": [{"loc": ["parameters"], "message": "..."}]}
```
But after this fix, `rororo` again will produce,
```json
{"detail": [{"loc": ["parameters", "name"], "message": "..."}]}
```
error message.
> feature(openapi): Include param name to invalid schema error

- rororo/openapi/exceptions.py
- tests/test_openapi_exceptions.py
In addition to `ObjectDoesNotExist` add basic `BadRequest` error, which is not used by `rororo` internally, but might be useful for external projects.
> feat(openapi): Provide basic bad request error

- rororo/openapi/openapi.py
- tests/test_openapi.py
- tests/test_openapi_middlewares.py
Previously it only be possible to use default `rororo` error handler in `error_middleware`, but sometimes it is needed to redefine that, for example when web application served both API & non-API (HTML) pages.
> feat(openapi): Allow to redefine default error handler

- .github/workflows/ci.yml
In reality there is no need to test job wait on build job to succeed. If the build job will fail, test job will cancelled. Which means, running build & test jobs in parallel will speed up CI execution times.
> ci: Run build & test jobs in parallel

- examples/hobotnica/openapi.yaml
- examples/hobotnica/tests.py
- examples/hobotnica/views.py
Ensure that patched path finder select proper path.
For example for paths,
- `/api/repositories/favorites`
- `/api/repositories/{owner}`
it will select first one for request `GET /api/repositories/favorites`.
> test(openapi): Provide more tests for custom path finder

- CHANGELOG.rst
- docs/index.rst
- docs/openapi_issues.rst
- docs/openapi_speedups.rst
- docs/settings.rst
- rororo/openapi/openapi.py
- tests/test_openapi.py
As well as use `yaml.CSafeLoader` instead of `yaml.SafeLoader` when possible.
Fixes: #61
> perf(openapi): Allow to pass custom schema loader function

- .github/workflows/ci.yml
- docs/api.rst
- docs/openapi_speedups.rst
- examples/hobotnica/app.py
- examples/todobackend/app.py
- rororo/openapi/openapi.py
- rororo/openapi/views.py
- tests/test_openapi_openapi.py
This is highly experimental feature which is designed to be useful only for test environments, where ``setup_openapi`` called more than once per process flow.
> perf(openapi): Allow to cache create schema and spec for test env

- CHANGELOG.rst
Fix:
----
- When possible pass request body as string to `OpenAPIRequest`, not as bytes
Style:
------
- Update pre-commit hooks, integrate `flake8-variable-names`
> chore(release): 2.0.0rc2 Release

- CHANGELOG.rst
- Makefile
- rororo/openapi/openapi.py
- tests/test_openapi_openapi.py
Previously it only handles `OpenAPIValidationError` exceptions, which resulted in bad user experience in case of other errors, such as `JSONDecodeError` (when OpenAPI schema is not valid JSON file).
Fixes: #74
> fix: Handle all errors on creating OpenAPI spec from schema

- docs/openapi.rst
- rororo/openapi/openapi.py
- tests/test_openapi.py
- tests/test_openapi_openapi.py
Previously *rororo* relies only on `schema_path` positional argument and does read schema from path and instantiate spec instance inside of `setup_openapi` call.
This commit allows to directly path `schema` and `spec` keyword args to `setup_openapi`, which gives developers wider range of caching / reusing schema & spec for environments, which needs to instantiate `web.Application` (and call `setup_openapi`) a lot.
Fixes: #84
> feat(openapi): Allow passing `schema` and `spec` keyword args to `setup_openapi`

- CHANGELOG.rst
Features:
---------
- Allow passing `schema` and `spec` keyword args to `setup_openapi` (#86)
Fixes:
------
- Handle all errors on creating OpenAPI spec from schema (#74)
- Allow nullable arrays & objects in request/response data (#85)
Other:
------
- Cast return values instead of type ignore comments
- Do not include changelog into dist (#72)
- Update docs with new rororo slogan (#76)
- Create GitHub release at pushing git tag (#78)
- Bump pre-commit hooks
- Preserve multiline strings in release body (#78)
> chore: 2.0.0rc3 Release

- .pre-commit-config.yaml
- CHANGELOG.rst
- docs/requirements.in
- docs/requirements.txt
- pyproject.toml
- rororo/__init__.py
- tests/openapi.json
- tests/openapi.yaml
Final **2.0.0** release, which completes reimplementing *rororo* as library for implementing aiohttp.web OpenAPI 3 server applications with schema first approach.
[Docuementation](https://rororo.readthedocs.io/en/stable/openapi.html) provides more information on implementing aiohttp.web OpenAPI 3 server applications with schema first approach using *rororo*.
Fixes: #92
> chore: 2.0.0 Release

- .github/workflows/ci.yml
As well as,
- Use github token for coveralls
- Fix creating releases from action
Fixes: #95
> ci: Bump github actions to use

- CHANGELOG.rst
- pyproject.toml
- src/rororo/__init__.py
- tests/openapi.json
- tests/openapi.yaml
Features:
---------
- Depend on `attrs>=19.1,<21` to allow install `attrs==20.1.0` in dependent projects
Other:
------
- Massive infrastructure update: move code to `src/` directory, use latest `pytest` for tests, better `Makefile` targets, etc
> chore: 2.0.2 Release

- examples/simulations/app.py
- examples/simulations/openapi.yaml
- src/rororo/openapi/openapi.py
- src/rororo/openapi/security.py
If OpenAPI operation setup security as empty list it means that given operation is unsecured even the OpenAPI spec has defined default security schema.
Fix `rororo` security handling to ensure given case. Previously it results in inability of using unsecured operations if OpenAPI schema defines default `security`.
Fixes: #114
> fix(openapi): Proper handling of operations with empty security list

- examples/hobotnica/src/hobotnica/openapi.yaml
- examples/hobotnica/src/hobotnica/views.py
- src/rororo/openapi/annotations.py
- src/rororo/openapi/openapi.py
- src/rororo/openapi/security.py
- tests/examples/hobotnica/test_hobotnica.py
If the operation schema does not contain `security` - properly set it to `None` instead of using empty security list from `openapi_core`. This allows properly handle operations with empty security schemas and use global security schema in case of missed operation security.
Fixes: #117
> fix: Proper handling of operations with empty security list

- examples/hobotnica/src/hobotnica/openapi.yaml
- src/rororo/openapi/openapi.py
Properly understand cases, where `parameters` list defined for whole path as follows,
```yaml
"/path/{param}":
parameters:
- $ref: "#/components/parameters/Param"
```
Fixes: #127
> fix(openapi): Allow to use parameters within path object

- src/rororo/openapi/annotations.py
- src/rororo/openapi/constants.py
- src/rororo/openapi/core_validators.py
- src/rororo/openapi/openapi.py
- src/rororo/openapi/utils.py
- src/rororo/openapi/validators.py
- tests/rororo/test_openapi_core_validators.py
*rororo* using [email-validator](https://github.com/JoshData/python-email-validator) library for validating email strings.
In most cases `validate_email(email)` call should be enough, but when not it is now possible to pass `validate_email_kwargs` dict such as follows,
```python
app = setup_openapi(
web.Application(),
Path(__file__).parent / "openapi.json",
operations,
validate_email_kwargs={"check_deliverability": False},
)
```
Fixes: #133
> feat(openapi): Allow to pass kwargs to validate email func

- Makefile
- docs/api.rst
- docs/openapi_errors.rst
- docs/requirements.txt
- poetry.lock
- pyproject.toml
- src/rororo/openapi/__init__.py
- src/rororo/openapi/exceptions.py
- tests/rororo/test_openapi.py
- tests/rororo/test_openapi_exceptions.py
Introduce `validation_error_context` to allow reuse validators and raising validation errors within `aiohttp.web` applications.
Also allow to combine (merge, add) `ValidationError` exceptions.
Finally provide documentation for raising custom errors from OpenAPI handlers.
Fixes: #100
Fixes: #132
> feat(openapi): Improve validation errors

- poetry.lock
- pyproject.toml
Previously rororo allows to install `openapi-core==0.13.7` and `openapi-core==0.13.8` which is not yet supported.
This commit pin supported version of `openapi-core` to `>=0.13.3,<0.13.7` which ensure that `poetry update` do not break your environment.
Issue: #149
> build: Pin supported openapi-core version

- .pre-commit-config.yaml
- examples/hobotnica/src/hobotnica/openapi.yaml
- src/rororo/openapi/openapi.py
Previously on fixing spec operations *rororo* assumes that operation ID is always present, but due to specification `operationId` should be treat as an optional value and may be missed for some, not yet implemented operations.
This commit fixes the assumption by treating `operationId` as an optional value.
> fix: Ensure that Operation ID is an optional value

- docs/requirements.txt
- poetry.lock
- pyproject.toml
While `rororo` not direclty depends on `typing-extensions`, as `aiohttp` depends on given library, add `typing-extensions` to *rororo* dependencies.
> build: Depend on typing-extensions

- poetry.lock
- pyproject.toml
Loose `PyYAML` dependency to allow dependent projects install its latest version in **6.0**.
> build(deps): bump PyYAML from 5.4.1 to 6.0

- CHANGELOG.rst
- pyproject.toml
- src/rororo/__init__.py
- tests/rororo/openapi.json
- tests/rororo/openapi.yaml
Use Python 3.10 as dev version, as well as update minimum supported `openapi-core` version to **0.13.4**.
Also loose a bit `pyrsistent` & `PyYAML` requirements to allow dependent projects use latest versions of given libraries.
Other:
------
- (**deps**) bump actions/cache from 2.1.5 to 2.1.6 (#185)
- (**deps**) bump peter-evans/create-pull-request from 3.8.2 to 3.10.0 (#186)
- (**deps**) bump environ-config from 21.1.0 to 21.2.0 (#183)
- (**deps-dev**) bump pytest-cov from 2.11.1 to 2.12.1 (#187)
- (**deps**) bump email-validator from 1.1.2 to 1.1.3 (#190)
- (**deps**) bump pyrsistent from 0.17.3 to 0.18.0 (#189)
- (**deps**) bump urllib3 from 1.26.4 to 1.26.5 in /docs (#188)
- (**deps-dev**) bump aioredis from 1.3.1 to 2.0.0 (#192)
- (**deps**) bump tibdex/github-app-token from 1.3 to …
> chore: 2.3.0 Release

- .github/workflows/release_tag.yml
- Makefile
- README.rst
- poetry.lock
- pyproject.toml
- src/rororo/annotations.py
- src/rororo/openapi/core_data.py
As well as bump minimum `aiohttp` supported version to **3.7.0** and bump `aiohttp-middlewares` dependency as well.
> feat: Ensure support of aiohttp 3.8.0 version

- .github/actions/install_python_and_poetry/action.yml
- .github/actions/run_pre_commit/action.yml
- .github/actions/run_tox/action.yml
- .github/workflows/ci.yml
- .github/workflows/ci_package.yml
- .github/workflows/ci_release.yml
- .github/workflows/ci_verify_docs_build.yml
- .github/workflows/release_pr.yml
- .github/workflows/release_tag.yml
- .pre-commit-config.yaml
- Makefile
- poetry.lock
- pyproject.toml
- python.mk
Bump project deps to latest possible versions, as well as bump pre-commit hooks and CI actions to use.
Also provide `make test-%` target to run tests for specific tox env without setting `TOXENV` var (this saves only couple of keypresses, but still feels cool :sunglasses:).
> build: Monthly maintenance (Jan 2023)

- Makefile
- examples/hobotnica/src/hobotnica/app.py
- examples/hobotnica/src/hobotnica/openapi.yaml
- examples/hobotnica/src/hobotnica/settings.py
- examples/hobotnica/src/hobotnica/views.py
- src/rororo/openapi/middlewares.py
- tests/examples/hobotnica/test_hobotnica.py
Previously `rororo` has setup error middleware to handle `web.HTTPRedirection` errors as any other error, which is not valid behaviour as those errors should be treated as **redirections** instead.
Fixes: #191
> fix(openapi): Do not handle redirection errors

- .github/workflows/ci.yml
- Makefile
- examples/vc-api/README.rst
- examples/vc-api/src/vc_api/app.py
- examples/vc-api/src/vc_api/examples.py
- examples/vc-api/src/vc_api/vc-api.yaml
- examples/vc-api/src/vc_api/views.py
- pyproject.toml
- tests/examples/vc_api/test_views.py
With `openapi-core>=0.13.4,<0.13.7` it is impossible to support following **valid** schema of,
```
Component:
type: "object"
oneOf:
- type: "string"
- type: "object"
...
```
as it does not negate global `type: "object"`, when resolves inner `type: "string"`.
Cause of that provide a test, but mark it as XFAIL, and hopefully the problem will gone with migration to latest `openapi-core` 🤔
Issue: #159
Related: #149
> test(openapi): Cover oneOf schema from Verifiable Credential API with test
